### ISSUE TITLE
Weird interaction with this wallpaper

### ISSUE THREAD

**Issue by surajmandalcell** [elementary/wingpanel#115]
Is this normal? Looks weird to me

Bug screenshot :
![image](https://user-images.githubusercontent.com/11650177/40886134-6da3668c-6750-11e8-8ead-70aaf38fe2cd.png)

Wallpaper : 
![background3](https://user-images.githubusercontent.com/11650177/40886118-42effc66-6750-11e8-88e3-870b6168512c.jpg)

**Comment by ryonakano** [comment]
This is not a bug, please see [this official post](https://medium.com/elementaryos/juno-progress-for-january-february-9b276042716e)

**Comment by donadigo** [comment]
First: if you use daily repo or you built wingpanel from source, this is the new styling that will be present in Juno for light wallpaper. @ryonakano already linked to the 
relevant blog post.

Second: the panel is white and not transparent because then the Applications label wouldn't be visible with the dark background of this tree.

**Comment by surajmandalcell** [comment]
Ok, btw is there a way to get this to force set to at-least dark wingpanel one?

**Comment by ryonakano** [comment]
@surajmandalcell I'm not sure, but I suppose there is no way to do that...
