### ISSUE TITLE
Wingpanel cannot start when logging in over xrdp

### ISSUE THREAD

**Issue by Extravert-ir** [elementary/wingpanel#160]
Here is what's being printed in console:
```
victor@victor-pc:~$ wingpanel
[INFO 08:44:31.713668] Application.vala:153: System Panel version: 2.0.4
[INFO 08:44:31.713704] Application.vala:155: Kernel version: 4.15.0-36-generic
[FATAL 08:44:31.794968] [GLib-GIO] g_dbus_connection_call_internal: assertion 'object_path != NULL && g_variant_is_object_path (object_path)' failed
```

**Comment by davidmhewitt** [comment]
There's not a lot of information in that error message that allows us to pin down what's causing that. If possible, could you run wingpanel under gdb and get a backtrace by doing the following.

- Install gdb if not already installed.
- `gdb wingpanel`
- Type `run` and hit enter
- When it crashes, type `bt` and hit enter
- Copy&Paste output or get a screenshot or a photo if you can't copy

However, from your description of trying to use xrdp, this is probably fixed by this PR:
https://github.com/elementary/wingpanel-indicator-session/pull/60

If you are able, you could try building and installing the session indicator from that branch and seeing if it fixes your issue.

**Comment by Extravert-ir** [comment]
Built version 2.0.4 with changes from your PR and it works. Thanks!

**Comment by davidmhewitt** [comment]
Great, thanks for confirming. I'll move this issue over to the session indicator repository so it can be tracked there. Hopefully that PR will make it into the next release of the indicator.
