### ISSUE TITLE
Wingpanel moves 

### ISSUE THREAD

**Issue by Yansen92** [elementary/wingpanel#169]
The wingpanel bar moves from the top center for some reason. Haven't found what triggers it, but it has happened every day since I installed Juno. It always moves to the exact same spot and stays there unless I reboot.

I've tried to move it with my mouse and touchscreen but it stays there.  

I've attached a screenshot.

Thanks for your help.

![screenshot from 2018-10-25 17 00 30](https://user-images.githubusercontent.com/17573588/47535874-b6d7b600-d87a-11e8-9564-5868142e17a2.png)

**Comment by Yansen92** [comment]
Adding another screenshot 

![screenshot from 2018-10-25 17-02-29](https://user-images.githubusercontent.com/17573588/47536480-7c234d00-d87d-11e8-8500-7e1f41fdc9e7.png)

**Comment by Yansen92** [comment]
First time it moved elsewhere. 

![screenshot from 2018-10-26 12-42-16](https://user-images.githubusercontent.com/17573588/47586180-b8f25100-d91c-11e8-94fb-9eb1092bc228.png)

**Comment by peteruithoven** [comment]
@Yansen92 do you have a multitouch touchscreen by any change?

**Comment by peteruithoven** [comment]
Let's move some info from #176 here:

That author noticed that this might be caused by dragging on touchscreens using the following gesture from the top of the screen.
![group-women-hand-use-multi-touch-gestures-tablets-touc-screen-device-51041872](https://user-images.githubusercontent.com/25564840/48211380-002a0a00-e33f-11e8-8c78-75a8c1d604fe.jpg)

I am able to reproduce this on my Dell XPS 15 9550. 
Not sure how to prevent this. There doesn't seem to be an obvious Gtk.Window flag like `resizable` to prevent this.
I've tried returning `Gdk.EVENT_STOP` from the `Panel.button_press_event` but that doesn't seem to help.

**Comment by Yansen92** [comment]
@peteruithoven 

Yeah, Dell Inspiron 15 with touchscreen. 

Not sure if the issue is caused by touching the screen since I never really use it but I'll disable the touchscreen for a while to see if the issue re-appears.

**Comment by CSstefan** [comment]
This issue has been a real problem with the touchscreens on my POS terminals.  I've posted a bounty on this in the hopes someone can get Wingpanel to lockdown in place and not move with any touch actions.

**Comment by CSstefan** [comment]
I saw the fix pushed to master, but when does that push out to updates? I've updated terminals and it still moves.
