### ISSUE TITLE
Maximized app crosses Wingpanel

### ISSUE THREAD

**Issue by lucascenir** [elementary/wingpanel#192]
OS: elementary OS Juno
When I maximize a window, the app status bar crosses the panel, eating up a little bit of window as Wingpanel covers it.

## Expected behaviour:
![captura de tela de 2019-02-10 14 16 48](https://user-images.githubusercontent.com/14957594/52799289-ada86a00-3060-11e9-88fc-69b7989d2a69.png)

## What happens
![captura de tela de 2019-02-10 14 16 28](https://user-images.githubusercontent.com/14957594/52799386-dcbedb80-3060-11e9-8838-b5deee04716a.png)

## Additional info
However, when I restart Wingpanel with `killall wingpanel` it behaves as intended.

**Comment by stsdc** [comment]
Duplicate: #130

**Comment by Angedestenebres** [comment]
Even if issues https://github.com/elementary/wingpanel/issues/130 & https://github.com/elementary/wingpanel/pull/198 have been closed, I still get this issue :

![Capture d’écran de 2019-03-10 15-43-02](https://user-images.githubusercontent.com/21110485/54086794-f5af6980-434c-11e9-94ec-20e67c1802a9.png)

I can fix it quickly by killing the wingpanel but it appears again randomly when I restart or close my session. 

I thought it was related to update and the number displayed in the dock above the icon of the center apps but it also happens when I have no update available :/
I also noticed it can happen with different softwares / windows so I don't know the reason of this bug.

If I find something new about it, I'll post again here :)

It's not a blocking issue but it's a quite annoying.

**Comment by ryonakano** [comment]
@Angedestenebres There's been no new release of Wingpanel which includes the fix for this issue (#198), so this issue still should happen now. I think it should be fixed once a new version of Wingpanel is released.

**Comment by janxkoci** [comment]
It seemed to be resolved for a few weeks but now last few days I started to see it again.

**Comment by ryonakano** [comment]
Since now Wingpanel 2.2.3 is released, this issue should be no longer seen and can be closed.

**Comment by janxkoci** [comment]
Yeah seems fixed.

**Comment by codygarver** [comment]
Closed by #198
