### ISSUE TITLE
Window decoration blinks when i'm hovering over wingpanel

### ISSUE THREAD

**Issue by terrakok** [elementary/wingpanel#221]
![Запись экрана от 2019-06-13 14 42 19](https://user-images.githubusercontent.com/3532155/59430148-268ab900-8dea-11e9-8b7c-a86eb8487dec.gif)

**Comment by peteruithoven** [comment]
Good catch! I think this issue and https://github.com/elementary/wingpanel/issues/220 are related to whether the Wingpanel (this includes the indicator popovers) has focus. The window decoration probably blinks because it's switching between having focus and not having focus. 

There was one recent focus related change: https://github.com/elementary/wingpanel/pull/206.

**Comment by peteruithoven** [comment]
You also made me notice: https://github.com/elementary/wingpanel-indicator-notifications/issues/69
(Never noticed it because I have the power indicator (battery) inbetween)

**Comment by peteruithoven** [comment]
I actually think it's a race condition between the wingpanel restoring focus to a window and the wingpanel regaining focus. This race conditon might have worsened since this improvement: https://github.com/elementary/wingpanel/pull/155

**Comment by DanyGee** [comment]
I can confirm exactly the same behavior on this machine, with additional problem of all new opened app windows going background instead of foreground:

>System:    Host: elementary-os Kernel: 4.15.0-54-generic x86_64 bits: 64 gcc: 7.4.0
           Desktop: Gnome  (Gtk 3.22.30) Distro: elementary OS 5.0 Juno
Machine:   Device: desktop Mobo: ASUSTeK model: Z170-DELUXE v: Rev 1.xx serial: N/A
           UEFI: American Megatrends v: 3504 date: 06/29/2017
CPU:       Quad core Intel Core i7-6700K (-MT-MCP-) arch: Skylake-S rev.3 cache: 8192 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 32064
           clock speeds: max: 4300 MHz 1: 1112 MHz 2: 3686 MHz 3: 3419 MHz 4: 3705 MHz 5: 3454 MHz 6: 3986 MHz
           7: 3828 MHz 8: 3809 MHz
Graphics:  Card: NVIDIA GP104 [GeForce GTX 1080] bus-ID: 01:00.0
           Display Server: x11 (X.Org 1.19.6 ) driver: nvidia Resolution: 3840x2160@60.00hz
           OpenGL: renderer: GeForce GTX 1080/PCIe/SSE2 version: 4.6.0 NVIDIA 430.26 Direct Render: Yes
Audio:     Card-1 Intel 100 Series/C230 Series Family HD Audio Controller driver: snd_hda_intel bus-ID: 00:1f.3
           Card-2 NVIDIA GP104 High Definition Audio Controller driver: snd_hda_intel bus-ID: 01:00.1
           Sound: Advanced Linux Sound Architecture v: k4.15.0-54-generic
Network:   Card-1: Intel Ethernet Connection (2) I219-V driver: e1000e v: 3.2.6-k bus-ID: 00:1f.6
           IF: enp0s31f6 state: up speed: 1000 Mbps duplex: full mac: <filter>
           Card-2: Broadcom and subsidiaries BCM4360 802.11ac Wireless Network Adapter
           driver: bcma-pci-bridge bus-ID: 07:00.0
           IF: N/A state: N/A mac: N/A
           Card-3: Intel I211 Gigabit Network Connection driver: igb v: 5.4.0-k port: c000 bus-ID: 0b:00.0
           IF: enp11s0 state: down mac: <filter>
Drives:    HDD Total Size: 2690.6GB (3.6% used)
           ID-1: /dev/nvme0n1 model: PCIe_SSD size: 120.0GB
           ID-2: /dev/sda model: Samsung_SSD_850 size: 256.1GB
           ID-3: /dev/sdc model: Crucial_CT1050MX size: 1050.2GB
           ID-4: /dev/sdd model: KINGSTON_SH100S3 size: 120.0GB
           ID-5: /dev/sdb model: Samsung_SSD_850 size: 1024.2GB
           ID-6: /dev/sde model: KINGSTON_SV300S3 size: 120.0GB
Partition: ID-1: / size: 110G used: 91G (88%) fs: ext4 dev: /dev/sde1
RAID:      No RAID devices: /proc/mdstat, md_mod kernel module present
Sensors:   System Temperatures: cpu: 30.0C mobo: N/A gpu: 0.0:54C
           Fan Speeds (in rpm): cpu: 0
Info:      Processes: 293 Uptime: 8:00 Memory: 3850.8/64357.1MB Init: systemd runlevel: 5 Gcc sys: 7.4.0
           Client: Shell (bash 4.4.191) inxi: 2.3.56 

...and the same blinking on this machine, but here all new windows open normally in foreground:
>System:    Host: lenovo-c460 Kernel: 4.15.0-36-generic x86_64 bits: 64 gcc: 7.3.0 Desktop: Gnome  (Gtk 3.22.30)
           Distro: elementary OS 5.0 Juno
Machine:   Device: desktop System: LENOVO product: C460 v: Lenovo Product serial: N/A
           Mobo: LENOVO model: SHARKBAY v: 31900006 STD serial: N/A BIOS: LENOVO v: IMKT23AUS date: 05/18/2016
CPU:       Dual core Intel Core i3-4130T (-MT-MCP-) arch: Haswell rev.3 cache: 3072 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 11572
           clock speeds: max: 2900 MHz 1: 1301 MHz 2: 1392 MHz 3: 1449 MHz 4: 1217 MHz
Graphics:  Card-1: Intel 4th Generation Core Processor Family Integrated Graphics Controller bus-ID: 00:02.0
           Card-2: NVIDIA GF117M [GeForce 610M/710M/810M/820M / GT 620M/625M/630M/720M] bus-ID: 01:00.0
           Display Server: x11 (X.Org 1.19.6 ) drivers: modesetting (unloaded: fbdev,vesa)
           Resolution: 1920x1080@60.59hz
Audio:     Card-1 Intel 8 Series/C220 Series High Definition Audio Controller
           driver: snd_hda_intel bus-ID: 00:1b.0
           Card-2 Intel Xeon E3-1200 v3/4th Gen Core Processor HD Audio Controller
           driver: snd_hda_intel bus-ID: 00:03.0
           Sound: Advanced Linux Sound Architecture v: k4.15.0-36-generic
Network:   Card-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
           driver: r8169 v: 2.3LK-NAPI port: d000 bus-ID: 05:00.0
           IF: enp5s0 state: down mac: <filter>
           Card-2: Realtek RTL8188EE Wireless Network Adapter driver: rtl8188ee port: c000 bus-ID: 06:00.0
           IF: wlp6s0 state: up mac: <filter>
Drives:    HDD Total Size: 120.0GB (46.0% used)
           ID-1: /dev/sda model: KINGSTON_SA400S3 size: 120.0GB
Partition: ID-1: / size: 59G used: 52G (93%) fs: ext4 dev: /dev/sda1
RAID:      No RAID devices: /proc/mdstat, md_mod kernel module present
Sensors:   System Temperatures: cpu: 29.8C mobo: 27.8C gpu: 0.0:34C
           Fan Speeds (in rpm): cpu: N/A
Info:      Processes: 216 Uptime: 1 min Memory: 884.8/7890.0MB Init: systemd runlevel: 5 Gcc sys: 7.3.0
           Client: Shell (bash 4.4.191) inxi: 2.3.56

**Comment by peteruithoven** [comment]
I think I've solved it with #222 please feel free to give it a go, see if that solves it. 

(Btw, what kind of logs are those? Could use some context there)

**Comment by DanyGee** [comment]
Those logs are from **INXI** app.
I find it the most useful till date hardware listing app for bug reports.

>I think I've solved it with #222 please feel free to give it a go, see if that solves it.

Is there an easy way to try it without compiling too much? :sweat_smile:

**Comment by peteruithoven** [comment]
Seeing there is no such thing as compiling just a little, I'm afraid not ;)

**Comment by DanyGee** [comment]
I'll wait for an official update then.
THX!
