### ISSUE TITLE
Shut Down and Log Out dialogs lose focus

### ISSUE THREAD

**Issue by cassidyjames** [elementary/wingpanel#228]
Filed here and not on the session indicator because this is probably due to the self-unfocusing code of WingPanel?

**Comment by peteruithoven** [comment]
indeed I'm afraid so. 

But, maybe instead of coming up with a workaround for this use case, we can skip the dialog and add the individual buttons directly in the Popover? Just like this mockup from @lainsce: 
![session-indicator-popover_redesign](https://user-images.githubusercontent.com/523210/61255845-a64dcf80-a76a-11e9-9b6f-555ec9ca0267.png)

**Comment by Blast-City** [comment]
In the new dialog it should be possible to cancel with the Esc key.

Right now this is not possible.

**Comment by cassidyjames** [comment]
@Blast-City that's an entirely separate issue, I've filed it at https://github.com/elementary/wingpanel-indicator-session/issues/82
