### ISSUE TITLE
Distance between indicators

### ISSUE THREAD

**Issue by lesthack** [elementary/wingpanel#264]
I like wingpanel, but, honestly, i think that distance between indicators is very large.
So, I wish could change this:

From:
![default](https://firebasestorage.googleapis.com/v0/b/jorgeluis-com-mx.appspot.com/o/images%2F2019%2F08%2FScreenshot%20from%202019-08-26%2009-22-04.png?alt=media&token=5527a2de-e5fe-4e88-b72a-8b25e3ec15de)

Like that:
![after](https://firebasestorage.googleapis.com/v0/b/jorgeluis-com-mx.appspot.com/o/images%2F2019%2F08%2FScreenshot%20from%202019-08-26%2009-22-33.png?alt=media&token=54ccbe92-8409-401e-9e6c-a5dbf4c6668b)

**Comment by ernstki** [comment]
I agree that there's a exorbitant amount of negative space between indicator icons.

For what it's worth, this can be resolved by adding a simple GTK3 CSS style to `$HOME/.config/gtk-3.0/gtk.css`:

```css
/* source: https://github.com/mdh34/elementary-indicators/issues/1 */
.composited-indicator {
    padding: 0 2px;
}
```
[The issue where I found this solution](https://github.com/mdh34/elementary-indicators/issues/1#issuecomment-412634500) (in part, anyway) suggests editing ` /usr/share/themes/elementary-x/gtk-3.xx/apps.css`, but that path seems to be outdated, and it's just not necessary to edit the theme's CSS directly (as root). Just creating an override in `gtk.css` in your home directory seems to suffice.

**Comment by ernstki** [comment]
@lesthack P.S.: This is unlikely to get fixed, since it only affects third-party "application indicators," which "[have been deprecated for years](https://github.com/elementary/wingpanel/issues/96#issuecomment-401407354)." Application indicators are [considered an "anti-pattern"](https://medium.com/elementaryos/developer-tips-backgrounding-system-integration-31c1f7226606) in elementaryOS, and native elementary apps are encouraged to use app icon quicklists instead.

Don't get me wrong, I still want my Dropbox, ownCloud, Diodon, and AutoKey, and System Load Indicator (and so on) icons to have a nice tight spacing, but these third-party packages will never be updated to elementary standards, and this is not something the elementary core team is going to prioritize (for the reasons stated in that Medium post). I think overriding CSS styles as described above is about all your or I can hope for.

**Comment by lesthack** [comment]
@ernstki thank you, adding the css style works.

**Comment by ochornolutskyi** [comment]
Hello, @ernstki. 
Is this method still working for you? Nothing changed for me after adding styles
