### ISSUE TITLE
Make wingpanel shorter 

### ISSUE THREAD

**Issue by testgithub1212** [elementary/wingpanel#384]
The current wingpanel implementation takes so much precious vertical screen real estate; I would like  the height of the wingpanel to be reduced to get more screen real estate especially on laptops where vertical real estate is generally lacking. MacOS implementation seems way more laptop-friendly as the top bar is a bit shorter. Thanks in Advance..

**Comment by cassidyjames** [comment]
From a screenshot of my wife's work MacBook, it looks like the macOS panel is ~23dp (display pixels, or pixels @1x) tall, while it looks like WingPanel is ~30dp tall in elementary OS 6. Since we use a standard icon size and the icons are pixel-fit, the only thing we could easily do to change the size would be to reduce the vertical spacing around icons, but that would make them feel cramped—I don't think sacrificing the aesthetic balance is worth a vertical space saving of less than 10dp here.
