### ISSUE TITLE
Zoom (flatpak) doesn't close to status bar like with Gnome

### ISSUE THREAD

**Issue by Netherquark** [elementary/wingpanel#419]
### What Happened?

I installed Zoom and logged in. That was fine. After this, I closed the window but i couldn't see the Zoom logo in the right corner like I usually can with any distro having the Gnome DE (I'm only experienced with Gnome, and I presume Pantheon is based on the same, judging the look). So, I had to figure out how to kill the process, then start it again. If I close it, it remains running as a ghost of sorts and theres no way to open the window. One way to fix this might be the "AppStatusIndicator and KstatusItem and legacy Tray icons support" extension being bundled in by default. Not sure what the problem is, but this might be it. This experience ruined my introduction to Elementary OS. I'll be back later maybe. Sticking to Fedora for the time being.

### Steps to Reproduce

Install Zoom flatpak from flathub.org

Log in

Close the chat window

Try to open zoom

### Expected Behavior

Zoom closes to the status bar / tray and is openable from there

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
Not applicable
```

### Hardware Info

Tried this in a Oracle Virtualbox VM. Probably not relevant, but allocated 2GB and 1 core of my 2200G.

**Comment by msmaldi** [comment]
The elementary team will not do this. I abandoned the distro for this reason.

If you still want to try install:
https://github.com/Lafydev/wingpanel-indicator-ayatana

To add support for Legacy icons (Wine, PlayOnLinux) see here : [msmaldi/wingpanel-indicator-na-tray](https://github.com/msmaldi/wingpanel-indicator-na-tray)

**Comment by Netherquark** [comment]
Well thats lame. Guess ill stick to fedora. Thanks for the help anyways

**Comment by danrabbit** [comment]
Thanks for filing an issue report! Pantheon is an independent desktop environment and it isn't based on GNOME Shell.

The 3 contemporary "systray" APIs are not compatible with sandboxed apps and won't work on Wayland, so we have no plans to add support for these APIs. You can read a more in-depth explanation here: https://www.reddit.com/r/gnome/comments/qsub7c/comment/hkg7mo1/?utm_source=share&utm_medium=web2x&context=3

Closing as "Out of scope" since desktops are going to remove these APIs and apps should use modern APIs like the background portal and desktop launcher actions
