### ISSUE TITLE
Space between icons in Wingpanel (Intel graphics)

### ISSUE THREAD

**Issue by BrusAndr** [elementary/wingpanel#80]
When I switch to Intel graphics, there are spaces between the icons, like this:
![screenshot from 2018-01-07 11 51 28](https://user-images.githubusercontent.com/29145756/34647973-defaf4d0-f3a1-11e7-86c8-ce63b28ee395.png)
But everything is normal for Nvidia:
![screenshot from 2018-01-07 11 50 22](https://user-images.githubusercontent.com/29145756/34647980-15ae4fae-f3a2-11e7-92d1-6a0c54b33fe3.png)
My system:
![image](https://user-images.githubusercontent.com/29145756/34647990-2b616fc0-f3a2-11e7-8477-34e122efba90.png)
elementaryOS 0.4.1 stable
Intel i7-7700HQ
Intel HD Graphics 630
NVidia Quadro M1200

**Comment by Philip-Scott** [comment]
There might be something wrong with your config for the Intel graphics, i'm guessing that the "frame-rate" of the UI is a but low, right? Specially if you go to the multitasking view? :wink: 

That space you have happens when things are being rendered without hardware acceleration. (Which means that it's actually not using your Intel Graphics card). 

If you want the specifics, both indicators also have "more" than just the icon. The power has the battery percentage and the sound pops out a mic when something is using it. And without hardware acceleration GTK requests the full size it _could_ need

**Comment by BrusAndr** [comment]
Here is my `/etc/X11/xorg.conf.d/20-intel.conf`
```
Section "Device"
    Identifier "intel"
    Driver "modesetting"
    BusID "PCI:0@0:2:0"
    Option "AccelMethod" "sna"
    Option "TearFree" "true"
EndSection
```

**Comment by Philip-Scott** [comment]
I'm also an intel graphics user and don't have that file on my machine, so i couldn't say. It may not be just that, but maybe somewhere else that you changed in order to swap from using nvidia to intel.

**Comment by BrusAndr** [comment]
I didn't change anything else.

**Comment by BrusAndr** [comment]
I disabled `/etc/X11/xorg.conf.d/20-intel.conf` and now all is ok.
