### ISSUE TITLE
Support global menu for regular app with menues

### ISSUE THREAD

**Issue by mojo2012** [elementary/wingpanel#81]
Many okd fashioned apps, like libre office or eclipse can‘t be used without menus. Currently they are rendered within the application window, each in with it‘s own styles. Besides the fact that this doesn‘t fit into the elementaryos experiece, it‘s aslo plain ugly.

A good solution would be to include them in the wingpanel like ‚super-wingpanel’ does (currently unmaintained).
For this to work the date picker would have to be moved to the right though.
When using ubuntu‘s appmenußindicator this should be fairly easy to integrate too.

It could look loke this: https://goo.gl/images/zMDpPW

**Comment by cassidyjames** [comment]
Apps designed for elementary OS do not use a menu bar. Legacy and cross-platform apps that do use a menu bar have been written assuming that element is in the application where the developer put it. We don't plan to write extra code to rip UI elements out of application windows and place them in the OS chrome, especially when this pattern doesn't make sense in the context of the elementary OS HIG and applications.

**Comment by mojo2012** [comment]
i partly disagree, apps like eclipse are cross platform, but many other native linux apps have menubars too. Don‘t you want to try to make those feel at home too?
I‘d be ok with a unified title/menubar too.
There are many regular apps you can‘t just ignore or find an elementary os alternative. It‘s a shame that those apps look so ugly and don‘t fit into the elementary UI at all :\

**Comment by gagarine** [comment]
Most app should have menu.  A desktop is not a phone.
https://medium.com/@probonopd/make-it-simple-linux-desktop-usability-part-1-5fa0fb369b42

**Comment by cassidyjames** [comment]
@gagarine elementary OS has an extensive set of [Human Interface Guidelines](https://elementary.io/docs/human-interface-guidelines), which are not up for debate in the scope of this issue.

**Comment by gagarine** [comment]
@cassidyjames that's a good! Sadly, I didn't find how to propose a HIG/Design change.

**Comment by developer91234** [comment]
@cassidyjames 

There is a very simple solution: integrate menubars into the HIG spec and allow it to be toggled (hidden/shown). That's it. Mac has menubars and headerbars, KDE has menubars that you can hide in every single app. Chrome has a hidden menubar, and I was really shocked by how much nicer it was than their hamburger menu (which I still can't get a handle on after using this browser for a decade!).

As it stands, the HIG "guideline" necessarily **excludes any application more complex than a CD burner**, is tied to Gnome, requires developers to waste time reinventing the UI and introduces terrible fragmentation into the linux desktop.  HIG depreciates an element that was standard, familiar, structured, discoverable, easy to hit, compact, keyboard macro optimized, uniform and (with Unity) fully searchable and space-saving. That's a terrible decision.

All of these problems could be solved by putting out a guideline that accommodates both headerbars and menubars. **Porting apps like Gimp, Office and Evolution to HIG/CSD would finally be possible.** (I know Office has some alpha-quality "ribbon UI", but that's not HIG, and also a terrible idea.)  **Global menus would again be possible, HUD would be possible, etc.** Possible doesn't mean everyone has to use it. If someone would rather navigate a bunch of different widgets, tabs, hamburger menus and shortcut cheat-sheets (yes, you now have to pull up and memorize a cheatsheet to explore shortcuts in Gnome apps) they are still free to do so!

You can always lock-down and dumb-down an interface, but you need to start with a rich and flexible model.

Without the menubar, HIG cannot be a "guideline for desktop applications." It's just a directive to cram as many heterogeneous menus and widgets into the titlebar, creating a blob that can never be modified because there is no structure to work on. This means that Linux apps become like Windows - zero consistency, zero customization.

Gnome designers will not heed even an ounce reason regardless of the source: neither from users, nor other projects like KDE, nor from software giants like Apple. I sincerely hope Elementary can save the day here by fixing the HIG guideline. No need to hack together your own global menu or HUD just yet. **Just update the guideline to accommodate both headerbars and menu bars. That's it.**

**Comment by cassidyjames** [comment]
@developer91234 again, the HIG is not up for debate within the scope of this issue. Apps with menubars do and will continue to work on elementary OS with their menubars exactly where the developers put them. The HIG is our opinionated set of guidelines for apps, but they're guidelines. If an app wants a menubar, it can put a menubar in its window.
