### ISSUE TITLE
Date format is no longer configurable

### ISSUE THREAD

**Issue by MathyM** [elementary/wingpanel#91]
There used to be a `custom-time-format` available option in `com.canonical.indicator.datetime`

That is no longer the case. The only option I have is to switch between 12h and 24h clocks.

**Comment by danrabbit** [comment]
Wingpanel itself doesn't draw the date time indicator and we don't use the Ubuntu indicator for drawing it either.

If you'd like to open a new issue report against the wingpanel date time indicator, the tracker for that is here: https://github.com/elementary/wingpanel-indicator-datetime

It would be hepful if you could be more specific about what you're expecting to see so we know exactly what's missing. It's unlikely that we'll have a completely freeform option here, but some options in addition to the AM/PM switch could be considered.

Going to close this for Wingpanel as "Out of Scope" since it can't be solved here.
